// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofuiwwzyqkrqyosljpnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdWl3d3p5cWtycXlvc2xqcG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzY1MjAsImV4cCI6MjA2NTUxMjUyMH0.WFrL3bQ2K5PQfCxD2cNHM4NApsDAgz50398R2uMWHgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);